import "./css/style.css";

import { Urbanist } from "next/font/google";
import { Providers } from "./providers";

const urban = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  display: "swap",
});

export const metadata = {
  title: "Style time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${urban.variable} font-urbanist antialiased bg-white text-gray-900 tracking-tight`}
        suppressHydrationWarning
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
